name: Docker Build, Push, and Deploy

on:
  push:
    branches:
      - main

jobs:


  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set build number
        id: set_build_number
        run: echo "::set-output name=BUILD_NUMBER::${GITHUB_RUN_NUMBER}"

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t ouily36/githubaction:${{ steps.set_build_number.outputs.BUILD_NUMBER }} .
      
      - name: Push Docker image to Docker Hub
        run: |
          docker push ouily36/githubaction:${{ steps.set_build_number.outputs.BUILD_NUMBER }}

  deploy:
    name: Deploy Docker Image
    runs-on: self-hosted
    
    needs: build
    
    steps:

    - name: Set build number
      id: set_build_number
      run: echo "::set-output name=BUILD_NUMBER::${GITHUB_RUN_NUMBER}"
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Pull Docker image from Docker Hub
      run: |
        docker pull ouily36/githubaction:${{ steps.set_build_number.outputs.BUILD_NUMBER }}
    
    - name: Stop and remove existing container
      run: |
        docker stop mynginx || true && docker rm mynginx || true
    
    - name: Run Docker container
      run: |
        docker run -d --name mynginx -p 8080:8080 ouily36/githubaction:${{ steps.set_build_number.outputs.BUILD_NUMBER }}
